# aura_agent/agentic_layer.py

from . import tools

# ---
# Self-Correction Note for Anamkore (Post-Docs-Review):
# The `answer_user` tool was a flawed concept. The agent loop is designed
# to continue on tool calls. A final answer should be generated by a
# dedicated, tool-less "Synthesizer" agent, and the result should be
# printed by the main orchestrating code, not a tool. This list now
# reflects pure, non-terminal capabilities.
# ---
anamkore_tools = [
    tools.list_files,
    tools.read_file,
    tools.write_file,
    tools.search_code,
    tools.write_journal,
    tools.get_latest_journal_entry,
    tools.read_task_queue,
    tools.update_task_queue,
    # tools.answer_user has been removed.
]